# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import servicio_pb2 as servicio__pb2


class PizzeriaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listo = channel.unary_unary(
                '/Pizzeria/Listo',
                request_serializer=servicio__pb2.Nulo.SerializeToString,
                response_deserializer=servicio__pb2.Nulo.FromString,
                )
        self.RegistraOrden = channel.unary_unary(
                '/Pizzeria/RegistraOrden',
                request_serializer=servicio__pb2.Orden.SerializeToString,
                response_deserializer=servicio__pb2.ConfirmacionOrden.FromString,
                )


class PizzeriaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Listo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistraOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PizzeriaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listo': grpc.unary_unary_rpc_method_handler(
                    servicer.Listo,
                    request_deserializer=servicio__pb2.Nulo.FromString,
                    response_serializer=servicio__pb2.Nulo.SerializeToString,
            ),
            'RegistraOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistraOrden,
                    request_deserializer=servicio__pb2.Orden.FromString,
                    response_serializer=servicio__pb2.ConfirmacionOrden.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pizzeria', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pizzeria(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Listo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pizzeria/Listo',
            servicio__pb2.Nulo.SerializeToString,
            servicio__pb2.Nulo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegistraOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pizzeria/RegistraOrden',
            servicio__pb2.Orden.SerializeToString,
            servicio__pb2.ConfirmacionOrden.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
